version: 2
jobs:
  build:
    environment:
      MAVEN_OPTS: -Xmx3200m

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps: # a collection of executable commands
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn test -Dgroups=AutoFW
      
      - run: |
          mkdir -p ~/repo/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/repo/junit/ \;

      - store_test_results:
          path: ~/repo/junit

      - store_artifacts:
          path: ~/repo/junit

workflows:
  version: 2
  workflow:
    jobs:
    - build 